Running Scheduled Experiment.
tcn_m2o_seq
experiments/experiment_params/tcn_m2o_norm_seq_1
tcn_m2o_norm_seq_1
Traceback (most recent call last):
  File "/home/tmarcu/.conda/envs/brain2brain_env/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/tmarcu/.conda/envs/brain2brain_env/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/tmarcu/brain2brain/brain2brain/__main__.py", line 65, in <module>
    main()
  File "/home/tmarcu/brain2brain/brain2brain/__main__.py", line 28, in main
    with open(args.experiment_json) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'experiments/experiment_params/tcn_m2o_norm_seq_1'
cp: cannot create regular file ‘tcn_m2o_norm_seq_1/tcn_m2o_norm_seq_1.log’: No such file or directory
