2020-04-02 03:28:28,996 DEBUG   MainThread:3196 [wandb_config.py:_load_defaults():122] no defaults not found in config-defaults.yaml
2020-04-02 03:28:29,028 DEBUG   MainThread:3196 [meta.py:setup():97] code probe starting
2020-04-02 03:28:29,030 DEBUG   MainThread:3196 [meta.py:_setup_code_git():49] probe for git information
2020-04-02 03:28:29,050 DEBUG   MainThread:3196 [meta.py:_setup_code_program():58] save program starting
2020-04-02 03:28:29,050 DEBUG   MainThread:3196 [meta.py:_setup_code_program():60] save program starting: /home/tmarcu/brain2brain/brain2brain/__main__.py
2020-04-02 03:28:29,051 DEBUG   MainThread:3196 [meta.py:_setup_code_program():65] save program saved: /home/tmarcu/brain2brain/tcn_experiment_m2o_4/wandb/dryrun-20200402_072827-dz4u8bp9/code/brain2brain/__main__.py
2020-04-02 03:28:29,051 DEBUG   MainThread:3196 [meta.py:_setup_code_program():67] save program
2020-04-02 03:28:29,052 DEBUG   MainThread:3196 [meta.py:setup():119] code probe done
2020-04-02 03:28:29,062 DEBUG   MainThread:3196 [run_manager.py:__init__():545] Initialized sync for brain2brain/dz4u8bp9
2020-04-02 03:28:29,065 INFO    MainThread:3196 [run_manager.py:wrap_existing_process():1148] wrapping existing process 3176
2020-04-02 03:28:30,004 INFO    Thread-3  :3196 [run_manager.py:_on_file_modified():692] file/dir modified: /home/tmarcu/brain2brain/tcn_experiment_m2o_4/wandb/dryrun-20200402_072827-dz4u8bp9/config.yaml
2020-04-02 03:28:35,101 INFO    MainThread:3196 [run_manager.py:init_run():928] system metrics and metadata threads started
2020-04-02 03:28:35,101 INFO    MainThread:3196 [run_manager.py:wrap_existing_process():1165] informing user process we are ready to proceed
2020-04-02 03:28:35,101 INFO    MainThread:3196 [run_manager.py:_sync_etc():1272] entering loop for messages from user process
2020-04-02 03:39:38,166 INFO    MainThread:3196 [run_manager.py:_sync_etc():1295] received message from user process: {"save_policy": {"glob": "wandb.h5", "policy": "live"}}
2020-04-02 03:39:38,236 INFO    MainThread:3196 [run_manager.py:_sync_etc():1295] received message from user process: {"exitcode": 0}
2020-04-02 03:39:38,236 INFO    MainThread:3196 [run_manager.py:_sync_etc():1381] closing log streams and sending exitcode to W&B
2020-04-02 03:39:38,237 INFO    MainThread:3196 [run_manager.py:shutdown():1072] shutting down system stats and metadata service
020-04-02 03:39:38,236 INFO    MainThread:3196 [dz4u8bp9:run_manager.py:_sync_etc():1381] closing log streams and sending exitcode to W&B
2020-04-02 03:39:38,237 INFO    MainThread:3196 [dz4u8bp9:run_manager.py:shutdown():1072] shutting down system stats and metadata service
