(36853, 114)
Traceback (most recent call last):
  File "/home/tmarcu/.conda/envs/brain2brain_env/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/tmarcu/.conda/envs/brain2brain_env/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/tmarcu/brain2brain/brain2brain/__main__.py", line 63, in <module>
    main()
  File "/home/tmarcu/brain2brain/brain2brain/__main__.py", line 59, in main
    gru_experiments.gru_m2o(experiment_params)
  File "/home/tmarcu/brain2brain/brain2brain/gru_experiments.py", line 343, in gru_m2o
    electrode_output_ix=config.electrode_out,
  File "/home/tmarcu/.conda/envs/brain2brain_env/lib/python3.7/site-packages/wandb/wandb_config.py", line 224, in __getattr__
    return self.__getitem__(key)
  File "/home/tmarcu/.conda/envs/brain2brain_env/lib/python3.7/site-packages/wandb/wandb_config.py", line 214, in __getitem__
    return self._items[key]
KeyError: 'electrode_out'
